### PR TITLE
spotlight effect

### PR DESCRIPTION
**Pull request by monty1289**
image
spotlight follows the player but seems to not lighten up the area that well

### CODE REVIEW

**Review by CalebStephens — DISMISSED** [review]
Just pulled it down, when i play i get a lovely pink screen for about 5seconds before it dissaperars and shows the game (without any spotlight), also on the spotlight game object  theres no script attached not sure if there is meant to be one or not, in image below you can see the pink screen and on the right the missing script 
Screenshot 2023-06-14 at 7 24 26 PM

**Comment by monty1289** [comment]
may need to download the universal pipeline from the package manager if the scene turns pink

**Comment by monty1289** [comment]
image
here is what the new version of the spotlight works

**Review by CalebStephens — APPROVED** [review]
Looks and plays way better, good work! I have created an issue for the expanding spotlight when you collect an artefact!

**Comment by MarcoKoen** [comment]
Awesome feature I think will help delay the game to 5 minutes! Cant wait to see it interact with our artefacts

**Pull request merged**
